version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  crossover-tests:
    image: rajesh23427/crossovertest:automationtest
    container_name: crossover-tests
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=crossover_tests.xml
      - BROWSER=CHROME
      - SELENIUM_HUB=selenium-hub
      - REMOTE=true